CUTE_PAPER_PROMPT = """CuTe is a Pythonic DSL built on CUTLASS that JITs CUDA kernels from Python. Write device kernels with `@cute.kernel`, wrap them with `@cute.jit` host functions, and compile with `cute.compile`. Layouts describe how multi-dimensional hierarchical indices map to linear memory, and tensors pair a pointer with memory space, dtype, alignment, and layout so you program in logical coordinates while CuTe handles address arithmetic. The contract appears as `tensor<ptr<f16, gmem, align<16>> o (M,N):(strideM,strideN)>`. Layouts use `S:D` notation (shape:stride) where row-major is `(M,N):(N,1)` and column-major is `(M,N):(1,M)`. Because layouts compose, you transform access patterns by composing layouts rather than rewriting pointer math.

Kernels are device functions with `@cute.kernel` taking `cute.Tensor` or `cute.Layout` arguments. Obtain CUDA indices via `tidx, _, _ = cute.arch.thread_idx()`, `bidx, _, _ = cute.arch.block_idx()`, `bdim, _, _ = cute.arch.block_dim()`. Index tensors with tuples in logical space for scalar access `val = gA[mi, ni]` or use hierarchy-aware slicing with `None` placeholders for vectorized access `gA[(None, (mi, ni))]`. Vectorized reads use `.load()` producing TensorSSA fragments manipulable with arithmetic, and writes assign back to sliced destinations like `gC[(None, (mi, ni))] = gA[(None, (mi, ni))].load() + gB[(None, (mi, ni))].load()`.

Host functions marked `@cute.jit` prepare layouts, configure tiling, compute launch configs, and return launchable kernels. Use `cute.zipped_divide(tensor, tiler)` to factorize layouts into "tile mode" and "remainder mode". A tiler like `(1, 4)` creates 4-wide vectors along the contiguous dimension, appearing as `((1,4),(M,N/4)):((0,1),(M,4))`. Compute dimensions with `cute.size(obj, mode=[k])` where `mode=[1]` is the block domain, and launch with `kernel(...).launch(grid=(gx,gy,gz), block=(bx,by,bz))`. Interop with PyTorch via `from_dlpack(t, assumed_align=16)` for zero-copy wrapping with alignment hints enabling wider vectors.

Create layouts with `make_layout(shape, stride=...)` where shape is a tuple of integers. Omitting stride gives compact column-major defaults, e.g., `make_layout((4,8))` yields shape `(4,8)` stride `(1,4)`. Specify custom strides like `stride=(8,1)` for row-major. Use keyword `stride=` to avoid confusion with hierarchical syntax. The E function creates unit basis elements like `E(0)` scalable as `4*E(0)`. Use `make_identity_layout(shape)` for coordinate-identity mapping with strides `(1@0,1@1,...)` or `make_ordered_layout(shape, order=(1,0))` to specify dimension ordering.

Thread-value (TV) layouts map thread id and per-thread vector lanes to tile coordinates, essential for scalable ML kernels. Build via `thr_layout = cute.make_layout((warp_groups,32), stride=(32,1))` for thread traversal and `val_layout = cute.make_layout((rows_per_thread,cols_per_thread), stride=(cols_per_thread,1))` for per-thread vectors. Then `tiler_mn, tv_layout = cute.make_layout_tv(thr_layout, val_layout)` produces block-tile size and `(tid,vid)→(TileM,TileN)` mapping. Thread layout must be compact. On host, tile tensors with `gA = cute.zipped_divide(mA, tiler_mn)`. In kernel, slice block tile `blkA = gA[((None,None), bidx)]`, compose to thread/value fragments `tidfrgA = cute.composition(blkA, tv_layout)`, slice to thread `thrA = tidfrgA[(tidx,None)]`. Read with `thrA.load()` fetching per-thread fragments as TensorSSA, write via per-thread views. This pattern decouples scheduling from math and enables coalesced vectorized access.

Create tensors with `make_tensor(ptr, layout)` composing an engine (pointer/iterator) with layout. Pointers via `make_ptr(dtype, tensor.data_ptr(), cute.AddressSpace.gmem, assumed_align=16)` where address space is `gmem`, `shared`, or `generic`. For register storage use `make_fragment(layout_or_shape, dtype)` or `make_fragment_like(src, dtype=None)` creating compact layouts. Identity tensors via `make_identity_tensor(shape)` generate coordinate sequences in colexicographic order. Tensors and layouts are immutable; create new ones via composition and slicing.

Layout algebra includes `composition(lhs, rhs)` where result R satisfies R(c)=A(B(c)), fundamental for expressing complex address mappings as simple transformations. The `complement(input, cotarget)` computes complementary layouts partitioning a space. Functions `right_inverse`, `left_inverse`, `max_common_layout`, and `max_common_vector` support inverse and common structure operations. Key manipulation functions: `get(input, mode=[...])` extracts sub-layouts by mode indices, `select(input, mode=[...])` chooses modes, `front(input)` gets first element at deepest level, `group_modes(input, begin, end)` groups mode ranges hierarchically, `coalesce(input)` simplifies by combining compatible strides. Query functions include `is_major(mode, stride)`, `leading_dim(shape, stride)`, `find(t, x)` searching hierarchies, and `find_if(t, pred_fn)` with predicates.

Hierarchical tuple operations: `transform_leaf(f, *args)` applies functions to leaves preserving structure, `flatten` and `flatten_to_tuple` convert to flat forms, `unflatten(sequence, profile)` reconstructs nesting. The `product(a)` computes element products with variants `product_like` and `product_each`. Extend structures with `prepend(input, elem, up_to_rank=...)` and `append(input, elem, up_to_rank=...)`, or use `prepend_ones` and `append_ones` for rank extension. Congruence checks via `is_congruent(a, b)` requiring matching rank and structure, or `is_weakly_congruent(a, b)` allowing scalar-tuple matches.

Partitioning operations include multiple divide variants (`zipped_divide`, `logical_divide`, `tiled_divide`, `flat_divide`) and product variants (`logical_product`, `zipped_product`, `tiled_product`, `flat_product`, `raked_product`, `blocked_product`) with different semantics. Use `ceil_div(input, tiler)` for ceiling division giving tile counts, `local_partition(target, tiler, index, proj=1)` for partitioning by index, and `local_tile(input, tiler, coord)` to extract specific tiles.

Copy operations use Copy Atoms encapsulating instructions and traits. Create with `make_copy_atom(op, copy_internal_type, **kwargs)` like `cute.nvgpu.CopyUniversalOp()` with args like `num_bits_per_copy=64`. Tiled copies via `make_tiled_copy_tv(atom, thr_layout, val_layout)` or `make_tiled_copy(atom, layout_tv, tiler_mn)`. Specialized constructors `make_tiled_copy_S/D` match source/destination layouts, and `make_tiled_copy_A/B/C` match MMA operand layouts. Execute with `copy(atom, src, dst, pred=None, **kwargs)` where tensors are partitioned per atom. TMA copies need `tma_bar_ptr=mbar_ptr, mcast_mask=mask`. Predication tensor profile must match `(ATOM_REST,REST_M,...)` when partitioned tensors are `((ATOM_V,ATOM_REST),REST_M,...)`. Simpler alternatives: `basic_copy(src, dst)` for element-wise when sizes match, `basic_copy_if(pred, src, dst)` with predication, `autovec_copy(src, dst)` auto-determining vector width. Use `prefetch(atom, src)` for TMA L2 prefetching. Single-threaded atoms auto-handle thread election.

MMA operations use MMA Atoms from `make_mma_atom(op)`. Tiled MMAs via `make_tiled_mma(op_or_atom, atom_layout_mnk=(1,1,1), permutation_mnk=None)` where `atom_layout_mnk` tiles atoms across threads and `permutation_mnk` tiles across values with permutation. Execute with `gemm(atom, d, a, b, c, **kwargs)` computing D=A*B+C where C and D can alias, supporting dispatch patterns: (V)x(V)=>(V), (M)x(N)=>(M,N), (M,K)x(N,K)=>(M,N), (V,M)x(V,N)=>(V,M,N), (V,M,K)x(V,N,K)=>(V,M,N). Some atoms like tcgen05 need runtime fields set via `tiled_mma.set(cute.nvgpu.tcgen05.Field.ACCUMULATE, True)` before execution. Query with `get(field)`. Tensors must be partitioned per atom.

Swizzle transforms permute elements via XOR for bank conflict reduction, defined by MBase (constant bits), BBits (mask bits), SShift (shift distance). Create composed layouts with `make_composed_layout(inner, offset, outer)` applying outer→offset→inner transformations. Use `recast_ptr(ptr, swizzle_=None, dtype=None)` and `recast_tensor(src, dtype, swizzle_=None)` for reinterpreting memory.

TensorSSA represents immutable thread-local data as IR values with nested shape and dtype. Created from loaded views, supports arithmetic (`x+y`, `x*y`), type conversion via `to(dtype)`, and construction with `full(shape, fill_value, dtype)`, `full_like(a, fill_value, dtype=None)`, `zeros_like(a)`, `ones_like(a)`, `empty_like(a)`. Methods include `broadcast_to(target_shape)` for broadcasting, `reduce(op, init_val, reduction_profile)` for reductions along specified modes, and `where(cond, x, y)` for conditional selection with auto-broadcasting.

Type system includes `cutlass.Float32`, `cutlass.Float16`, `cutlass.Int32`, `cutlass.Boolean`. Wrap immediates like `cutlass.Float32(1.0)`. Create pointers with `make_ptr(dtype, value, mem_space, assumed_align=...)`. Use `is_static(x)` to check compile-time knowledge, `size_in_bytes(dtype, layout)` for memory size, and `cosize(a, mode=[])` for codomain size (max offset + 1).

Utility functions: `printf(*args)` for formatted printing accepting values or format strings with C-style specifiers, `print_tensor(tensor, verbose=False)` outputting metadata and values, `crd2idx(coord, layout)` converting coordinates to indices, `filter_zeros(input)` removing zero-stride modes, `any_(x)` and `all_(x)` testing boolean tensors. Less critical utilities include `pretty_str`, `domain_offset`, `slice_and_offset`, `elem_less`, `round_up`, `shape_div`, `tile_to_shape`, `recast_layout`.

Struct abstraction with `@cute.struct` decorator defines C-like structures with scalar fields, `cute.struct.MemRange[dtype, size]` arrays, nested structs, and `cute.struct.Align[type, alignment]` for alignment. Query with `__sizeof__()` and `__alignof__()`. Access members via dot notation, index arrays, and create tensors from MemRange via `get_tensor(layout, swizzle=None, dtype=None)`.

Critical patterns: Always partition tensors/layouts before copy/gemm matching atom expectations. Single-threaded atoms auto-handle thread election. Check stride compatibility when composing as some compositions (Swizzle with ScaledBasis) are invalid. Use query functions (`is_static`, `cosize`, `is_congruent`) to verify properties. API favors small orthogonal composable pieces with elementwise arithmetic on fragments. Pass `cutlass.Constexpr` parameters for compile-time specialization. Follow functional style with immutable descriptors returning new objects. Maintain congruent/weakly-congruent nesting for hierarchical operations.

Typical workflow: (1) Convert PyTorch via `cute.from_dlpack(torch_tensor, assumed_align=16)`. (2) Construct tilers and TV layouts composing thread/value layouts. (3) Tile inputs with `zipped_divide`. (4) Compute launch dims via `cute.size` on tiler's `mode=[1]` and TV's `mode=[0]`. (5) Call `kernel(...).launch(grid=..., block=...)`. (6) JIT-compile with `cute.compile(host_fn, args...)` producing cached callable. For uneven tiles use predication helpers or build remainder handling into tiler/composition rather than branching. Keep vector widths consistent with `align<...>` specs, march tilers along contiguous strides for coalescing, prefer TV layouts over ad-hoc arithmetic for scalability. Always pass `loc=None, ip=None` unless needing MLIR diagnostics. Debug with `printf` and `print_tensor`. CuTe's power is separating computation (logical coords) from layout (memory pattern), enabling the same kernel to work efficiently across organizations/tilings/vectorizations by changing layout configs at host level.
"""